### ISSUE TITLE
Parameter required for id

### ISSUE THREAD

**Issue by panummi** [arq5x/lumpy-sv#82]
Hi,
I'm running LUMPY express, and I get message: "Parameter required for id". What is the parameter mentioned? Also, I've noticed that even though I run LUMPY express, it prints out options for traditional LUMPY (-g, -e, -w ...). What should I do?

**Comment by cc2qe** [comment]
Do your BAMs lack read group information in the header by any chance? In particular the SM read group field?

**Comment by nisanisa** [comment]
I have the same problem, but I do have SM read group information in the header. 
What should I do?

**Comment by cc2qe** [comment]
can you paste your command and the BAM header?

**Comment by nisanisa** [comment]
command:
lumpyexpress -B 87183.bam -S 87183.splitters.bam -D 87183.discordants.bam -o 87183.vcf

BAM header:
@HD	VN:1.4	SO:coordinate
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr20	LN:63025520
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr22	LN:51304566
@SQ	SN:chrX	LN:155270560
@SQ	SN:chrY	LN:59373566
@SQ	SN:chrM	LN:16571
@RG	ID:1	PL:nextseq	PU:IN708 LB:sureselect	SM:87183
@PG	ID:bwa	PN:bwa	VN:0.7.8-r455	
@PG	ID:MarkDuplicates	PN:MarkDuplicates	VN:1.97(1540)

**Comment by cc2qe** [comment]
ok thanks, could you run that command with the "-v" (verbose) flag and show the output?

**Comment by nisanisa** [comment]
Sourcing executables from /usr/local/bin/lumpyexpress.config ...

Checking for required python modules (/usr/bin/python)...

    create temporary directory
Calculating insert distributions... 
Library read groups: 1
Library read length: 151
Removed 108 outliers with isize >= 554
done
0
Running LUMPY... 

/home/nisa/scripts/sv_tools/lumpy-sv/bin/lumpy  \
    -t 87183.vcf.cPukn9w5zUKs/87183.vcf \
    -msw 4 \
    -tt 0 \
     \
     -pe bam_file:87183.discordants.bam,histo_file:87183.vcf.cPukn9w5zUKs/87183.vcf.sample1.lib1.x4.histo,mean:173.462708632,stdev:52.6397689291,read_length:151,min_non_overlap:151,discordant_z:5,back_distance:10,weight:1,id:,min_mapping_threshold:20,read_group:1 \
     -sr bam_file:87183.splitters.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:,min_clip:20 \
    > 87183.vcf
Parameter required for id

Program: ********** (v 0.2.11)
Author:  Ryan Layer (rl6sf@virginia.edu)
Summary: Find structural variations in various signals.

Usage:   ********** [OPTIONS] 

Options: 
	-g	Genome file (defines chromosome order)
	-e	Show evidence for each call
	-w	File read windows size (default 1000000)
	-mw	minimum weight for a call
	-msw	minimum per-sample weight for a call
	-tt	trim threshold
	-x	exclude file bed file
	-t	temp file prefix, must be to a writeable directory
	-P	output probability curve for each variant
	-b	output BEDPE instead of VCF
	-sr	bam_file:<file name>,
		id:<sample name>,
		back_distance:<distance>,
		min_mapping_threshold:<mapping quality>,
		weight:<sample weight>,
		min_clip:<minimum clip length>,
		read_group:<string>

	-pe	bam_file:<file name>,
		id:<sample name>,
		histo_file:<file name>,
		mean:<value>,
		stdev:<value>,
		read_length:<length>,
		min_non_overlap:<length>,
		discordant_z:<z value>,
		back_distance:<distance>,
		min_mapping_threshold:<mapping quality>,
		weight:<sample weight>,
		read_group:<string>

	-bedpe	bedpe_file:<bedpe file>,
		id:<sample name>,
		weight:<sample weight>

**Comment by cc2qe** [comment]
great thanks. It looks like lumpyexpress is unable to extract the sample ID from your BAM header and I have a feeling it's related to different flavors of awk. Could you send me the first ~10000 lines of each of your 3 BAM files so I can confirm? My email is colbychiang [at] wustl [dot] edu

It's possible that running the following before your lumpyexpress command will work, but send me your BAMs if you don't mind regardless:
```
alias awk=gawk
```

**Comment by nisanisa** [comment]
Now it's working. Thanks a lot!

**Comment by cc2qe** [comment]
ok, actually no need to send the BAMs then. I'll attempt to make that part more robust

**Comment by aliciab15** [comment]
Hi
I'm having the exact same problem as nisanisa with lumpyexpress. 
I've replaced awk with gawk but still get the same error message. Is there anything else that could fix this? 

here's the output I get:

./lumpyexpress -v -B AG1.bam -S AG1.splitters.bam -D AG1.discordants.bam -o AG1.vcf

./lumpyexpress -v -B AG1.bam -S AG1.bam -D AG1.discordants.bam -o AG1.vcf
Sourcing executables from lumpy-sv/bin/lumpyexpress.config ...

Checking for required python modules (/opt/gridware/pkg/apps/python/2.7.3/gcc-4.4.6/bin/python)...

    create temporary directory
Calculating insert distributions... 
done
Running LUMPY... 

/lumpy-sv//bin/lumpy  \
    -t AG1.vcf.JWUpzrZXTg9F/lumpytest7.vcf \
    -msw 4 \
    -tt 0 \
     \
     \
     -sr bam_file:AG1.splitters.bam,back_distance:10,min_mapping_threshold:20,weight:1,id:,min_clip:20 \
    > AG1.vcf
Parameter required for id

Program: ********** (v 0.2.12)
Author:  Ryan Layer (rl6sf@virginia.edu)
Summary: Find structural variations in various signals.

Usage:   ********** [OPTIONS] 

Options: 
	-g	Genome file (defines chromosome order)
	-e	Show evidence for each call
	-w	File read windows size (default 1000000)
	-mw	minimum weight for a call
	-msw	minimum per-sample weight for a call
	-tt	trim threshold
	-x	exclude file bed file
	-t	temp file prefix, must be to a writeable directory
	-P	output probability curve for each variant
	-b	output BEDPE instead of VCF
	-sr	bam_file:<file name>,
		id:<sample name>,
		back_distance:<distance>,
		min_mapping_threshold:<mapping quality>,
		weight:<sample weight>,
		min_clip:<minimum clip length>,
		read_group:<string>

	-pe	bam_file:<file name>,
		id:<sample name>,
		histo_file:<file name>,
		mean:<value>,
		stdev:<value>,
		read_length:<length>,
		min_non_overlap:<length>,
		discordant_z:<z value>,
		back_distance:<distance>,
		min_mapping_threshold:<mapping quality>,
		weight:<sample weight>,
		read_group:<string>

	-bedpe	bedpe_file:<bedpe file>,
		id:<sample name>,
		weight:<sample weight>

Thanks for your help!

**Comment by cc2qe** [comment]
can you post your BAM header?

**Comment by cc2qe** [comment]
also, are all of your BAM files (full, splitters, and discordants) coordinate-sorted?
Do they have "@HD	VN:1.3	SO:coordinate" as the first line of the header?

**Comment by aliciab15** [comment]
@HD	VN:1.3	SO:coordinate
@SQ	SN:NC_027300.1	LN:159038749
@SQ	SN:NC_027301.1	LN:72943711
@SQ	SN:NC_027302.1	LN:92503428
@SQ	SN:NC_027303.1	LN:82398023
@SQ	SN:NC_027304.1	LN:80503876
@SQ	SN:NC_027305.1	LN:87043187
@SQ	SN:NC_027306.1	LN:58785265
@SQ	SN:NC_027307.1	LN:26434011
@SQ	SN:NC_027308.1	LN:141712163
@SQ	SN:NC_027309.1	LN:116138521
@SQ	SN:NC_027310.1	LN:93888508
@SQ	SN:NC_027311.1	LN:91880962
@SQ	SN:NC_027312.1	LN:107758822
@SQ	SN:NC_027313.1	LN:93901823
@SQ	SN:NC_027314.1	LN:103963436
@SQ	SN:NC_027315.1	LN:87796322
@SQ	SN:NC_027316.1	LN:57682537
@SQ	SN:NC_027317.1	LN:70695409
@SQ	SN:NC_027318.1	LN:82978132
@SQ	SN:NC_027319.1	LN:86795997
@SQ	SN:NC_027320.1	LN:58021487
@SQ	SN:NC_027321.1	LN:63420196
@SQ	SN:NC_027322.1	LN:49854004
@SQ	SN:NC_027323.1	LN:48650976
@SQ	SN:NC_027324.1	LN:51481326
@SQ	SN:NC_027325.1	LN:47900953
@SQ	SN:NC_027326.1	LN:43943985
@SQ	SN:NC_027327.1	LN:39600944
@SQ	SN:NC_027328.1	LN:42488238
@PG	ID:bwa	PN:bwa	VN:0.7.12-r1039	CL:bwa mem -t 4 29chr.fna

**Comment by aliciab15** [comment]
Yes I sorted all my bam files

**Comment by cc2qe** [comment]
ok, you need to add readgroups with SM, ID, and LB information. https://github.com/ekg/bamaddrg is the easiest way to do so.

**Comment by aliciab15** [comment]
Ok I've added the read group header and now everything seems to be working. Thanks for your help with this!
